on: [push]
jobs:
  create_summary:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Add JUnit Summary
      uses: ./
      with:
        junit-path: src/debug/example.xml
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        FIREBASE_STORAGE_BUCKET: your-app.appspot.com
